# Generated by Django 3.0.4 on 2020-03-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
