# Generated by Django 2.2.12 on 2020-04-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0003_auto_20200414_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_shoe_status',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shoes',
            field=models.ManyToManyField(to='BEforDB.OrderList'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
