# Generated by Django 2.2.12 on 2020-04-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0004_auto_20200420_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DY', 'Delivery'), ('DE', 'Delivered'), ('P', 'Pacing'), ('NC', 'Not comfirmed')], max_length=2),
        ),
    ]
