# Generated by Django 2.2.12 on 2020-04-20 19:33

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0005_auto_20200420_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pacing'), ('DE', 'Delivered'), ('NC', 'Not comfirmed'), ('DY', 'Delivery')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
