# Generated by Django 2.2.12 on 2020-04-20 19:36

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0006_auto_20200420_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pacing'), ('DY', 'Delivery'), ('DE', 'Delivered'), ('NC', 'Not comfirmed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
