# Generated by Django 2.2.12 on 2020-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0010_auto_20200420_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pacing'), ('DE', 'Delivered'), ('DY', 'Delivery'), ('NC', 'Not comfirmed')], max_length=2),
        ),
    ]
