# Generated by Django 2.2.12 on 2020-04-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0011_auto_20200422_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DY', 'Delivery'), ('P', 'Pacing'), ('NC', 'Not comfirmed'), ('DE', 'Delivered')], max_length=2),
        ),
    ]
