# Generated by Django 2.2.12 on 2020-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0012_auto_20200422_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DE', 'Delivered'), ('P', 'Pacing'), ('DY', 'Delivery'), ('NC', 'Not comfirmed')], max_length=2),
        ),
    ]
