# Generated by Django 2.2.12 on 2020-04-22 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BEforDB', '0014_auto_20200422_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 14, 0, 7, 245197)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('DE', 'Delivered'), ('DY', 'Delivery'), ('P', 'Pacing'), ('NC', 'Not comfirmed')], max_length=2),
        ),
    ]
