# Generated by Django 2.2.12 on 2020-04-22 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0016_auto_20200422_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 15, 4, 5, 185518)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pacing', 'Pacing'), ('Delivered', 'Delivered'), ('Delivery', 'Delivery'), ('Not_Confirmed', 'Not confirmed')], max_length=20),
        ),
    ]
