# Generated by Django 2.2.12 on 2020-04-22 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0017_auto_20200422_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 15, 12, 23, 211587)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEforDB.Shoe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 15, 12, 23, 209554)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not_Confirmed', 'Not confirmed'), ('Delivery', 'Delivery'), ('Delivered', 'Delivered'), ('Pacing', 'Pacing')], max_length=20),
        ),
    ]
