# Generated by Django 2.2.12 on 2020-04-28 11:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0018_auto_20200422_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='BEforDB.Shoe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 14, 40, 41, 575960)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 14, 40, 41, 573965)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Delivery', 'Delivery'), ('Not_Confirmed', 'Not confirmed'), ('Pacing', 'Pacing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='size',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='BEforDB.Color'),
        ),
    ]
