# Generated by Django 2.2.12 on 2020-04-28 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0019_auto_20200428_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 21, 37, 10, 542173)),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEforDB.Color'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 21, 37, 10, 538187)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Pacing', 'Pacing'), ('Delivery', 'Delivery'), ('Not_Confirmed', 'Not confirmed')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
