# Generated by Django 3.0.5 on 2020-04-29 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0020_auto_20200429_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 17, 27, 20, 485801)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 17, 27, 20, 483942)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Not_Confirmed', 'Not confirmed'), ('Pacing', 'Pacing'), ('Delivery', 'Delivery')], max_length=20),
        ),
    ]
