# Generated by Django 2.2.12 on 2020-04-28 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0021_auto_20200428_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 0, 29, 50, 236610)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 0, 29, 50, 234611)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Pacing', 'Pacing'), ('Delivered', 'Delivered'), ('Not_Confirmed', 'Not confirmed')], max_length=20),
        ),
    ]
