# Generated by Django 2.2.12 on 2020-04-28 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0022_auto_20200429_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='shoe',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 0, 52, 59, 845120)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 0, 52, 59, 844123)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not_Confirmed', 'Not confirmed'), ('Delivered', 'Delivered'), ('Pacing', 'Pacing'), ('Delivery', 'Delivery')], max_length=20),
        ),
    ]
