# Generated by Django 2.2.12 on 2020-04-29 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0023_auto_20200429_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 17, 52, 37, 600811)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 17, 52, 37, 599814)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('Delivered', 'Delivered'), ('Not_Confirmed', 'Not confirmed'), ('Pacing', 'Pacing')], max_length=20),
        ),
    ]
