# Generated by Django 2.2.12 on 2020-05-01 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0024_auto_20200429_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 15, 22, 58, 704489)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 15, 22, 58, 702531)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pacing', 'Pacing'), ('Not_Confirmed', 'Not confirmed'), ('Delivered', 'Delivered'), ('Delivery', 'Delivery')], default='Not confirmed', max_length=20),
        ),
    ]
