# Generated by Django 2.2.12 on 2020-05-01 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BEforDB', '0025_auto_20200501_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 15, 28, 6, 270713)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 15, 28, 6, 268719)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not_Confirmed', 'Not confirmed'), ('Pacing', 'Pacing'), ('Delivered', 'Delivered'), ('Delivery', 'Delivery')], default='Not confirmed', max_length=20),
        ),
    ]
